version: '3.8'
services:
  web:
    image: python:3.12-slim
    container_name: flask-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: >
      sh -c "
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      gunicorn app:app --bind 0.0.0.0:5000
      "
